apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: grafana
    folders: grafana
  name: grafana
spec:
  config:
    auth:
      disable_login_form: "false"
    log:
      mode: console
    security:
      admin_user: admin
      admin_password: redhat
  route:
    spec:
      to:
        kind: Service
        name: grafana-service
        weight: 100