{
 "title": "ACS Key Risk Indicators",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Secured Cluster",
    "query": {
     "query": "label_values(acs_secured_cluster_info,secured_cluster_name)"
    }
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "CRITICAL : CRITICAL_VULNERABILITY_SEVERITY,IMPORTANT : IMPORTANT_VULNERABILITY_SEVERITY, MODERATE : MODERATE_VULNERABILITY_SEVERITY, LOW : LOW_VULNERABILITY_SEVERITY, UNKNOWN : UNKNOWN_VULNERABILITY_SEVERITY"
   },
   {
    "name": "fixable",
    "label": "Fixable",
    "query": "YES : true, NO : false, ANY : .*"
   }
  ]
 },
 "panels": [
  {
   "title": "Platform CVE's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  group by (cve) (\r\n    acs_vulnerable_cluster_info{severity=~\"$severity\", is_fixable=~\"$fixable\", secured_cluster_name=~\"$cluster\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CVE's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\r\n  group by (cve) (\r\n    acs_vulnerable_component_info{is_fixable=~\"$fixable\", severity=~\"$severity\"}\r\n    AND ON (component_name, component_version, component_operation_system)\r\n    acs_vulnerable_node_component_info{secured_cluster_name=~\"$cluster\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image CVE's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  group by (cve) (\r\n    (\r\n      acs_vulnerable_image_info{severity=~\"$severity\"}\r\n      AND ON (image_hash)\r\n      acs_vulnerable_deployment_info{secured_cluster_name=~\"$cluster\"}\r\n    )\r\n    AND ON (cve, image_hash)\r\n    acs_vulnerable_image_component_info{is_fixable=~\"$fixable\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique CVE Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  group by (cve) (\r\n    (\r\n      acs_vulnerable_cluster_info{secured_cluster_name=~\"$cluster\", severity=~\"$severity\", is_fixable=~\"$fixable\"}\r\n    )\r\n    or\r\n    (\r\n      acs_vulnerable_component_info{is_fixable=~\"$fixable\", severity=~\"$severity\"}\r\n      AND ON (component_name, component_version, component_operation_system)\r\n      acs_vulnerable_node_component_info{secured_cluster_name=~\"$cluster\"}\r\n    )\r\n    or\r\n    (\r\n      (\r\n        acs_vulnerable_image_component_info{is_fixable=~\"$fixable\"}\r\n        AND ON (cve)\r\n        acs_vulnerable_image_info{severity=~\"$severity\"}\r\n      )\r\n      AND ON (image_hash)\r\n      acs_vulnerable_deployment_info{secured_cluster_name=~\"$cluster\"}\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerability Distribution by Severity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (severity) (\r\n  group by (severity, cve) (\r\n    (\r\n      acs_vulnerable_cluster_info{secured_cluster_name=~\"$cluster\", severity=~\"$severity\", is_fixable=~\"$fixable\"}\r\n    )\r\n    OR\r\n    (\r\n      (\r\n        acs_vulnerable_image_info{severity=~\"$severity\"}\r\n        AND ON (cve)\r\n        acs_vulnerable_image_component_info{ is_fixable=~\"$fixable\"}\r\n      )\r\n      AND ON(image_hash)\r\n      acs_vulnerable_deployment_info{secured_cluster_name=~\"$cluster\"}\r\n    )\r\n    OR\r\n    (\r\n      acs_vulnerable_component_info{is_fixable=~\"$fixable\", severity=~\"$severity\"}\r\n      AND ON (component_name, component_version, component_operation_system)\r\n      acs_vulnerable_node_component_info{secured_cluster_name=~\"$cluster\"}\r\n    )\r\n\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Enviroment Impact", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Affected Clusters (Platform)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  group by (secured_cluster_name) (\r\n    acs_vulnerable_cluster_info{secured_cluster_name=~\"$cluster\", severity=~\"$severity\", is_fixable=~\"$fixable\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Affected Node Components",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\r\n  group by (component_name, component_version, component_operating_system) (\r\n    acs_vulnerable_component_info{is_fixable=~\"$fixable\", severity=~\"$severity\"}\r\n    AND ON (component_name, component_version, component_operating_system)\r\n    acs_vulnerable_node_component_info {secured_cluster_name=~\"$cluster\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Affected Images",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  group by (image_hash) (\r\n    acs_vulnerable_image_component_info{is_fixable=~\"$fixable\"}\r\n    AND ON (cve)\r\n    (\r\n      acs_vulnerable_image_info{severity=~\"$severity\"}\r\n      AND ON (image_hash)\r\n      acs_vulnerable_deployment_info{secured_cluster_name=~\"$cluster\"}\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Affected Workload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  group by (deployment_name, deployment_namespace, secured_cluster_name) (\r\n    (\r\n      acs_vulnerable_deployment_info{secured_cluster_name=~\"$cluster\"}\r\n      AND ON (image_hash)\r\n      (\r\n        acs_vulnerable_image_info{severity=~\"$severity\"}\r\n        AND ON (cve, image_hash)\r\n        acs_vulnerable_image_component_info{is_fixable=~\"$fixable\"}\r\n      )\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top 10", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "topk(10,\r\n  count by (secured_cluster_name) (\r\n    acs_vulnerable_cluster_info{secured_cluster_name=~\"$cluster\", severity=~\"$severity\", is_fixable=~\"$fixable\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "topk(10,\r\n  count by (node_name, secured_cluster_name) (\r\n      acs_vulnerable_node_component_info {secured_cluster_name=~\"$cluster\"}\r\n      AND ON (component_name, component_version, component_operating_system)\r\n      acs_vulnerable_component_info{is_fixable=~\"$fixable\", severity=~\"$severity\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "count by (image_remote) (\r\n  group by (image_remote, cve) (\r\n    (\r\n      acs_vulnerable_image_info{severity=~\"$severity\"}\r\n      AND ON (image_hash)\r\n      acs_vulnerable_deployment_info{secured_cluster_name=~\"$cluster\"}\r\n    )\r\n    AND ON (cve, image_hash)\r\n    acs_vulnerable_image_component_info{is_fixable=~\"$fixable\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}